### ISSUE TITLE
Unify workspace version

### ISSUE THREAD

**Issue by kulikthebird** [CosmWasm/cw-minus#29]
Some crates were moved from cw-plus to cw-minus and there was a decision to keep a single CHANGELOG for whole the workspace. In such a case all the crates should have the same version. The best way to unify it is to bump cw2 and cw-controllers to the current version of cw-utils.

**Comment by webmaster128** [comment]
Also let's add a shell script that updates the versions all at once. E.g. what we have in cosmwasm or cw-plus.
